[tool.ruff]
src = ["."]
exclude = ["migrations", ".venv", "env", "venv"]
target-version = "py311"
line-length = 100
fix = true

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
ignore = []

[tool.ruff.format]
quote-style = "single"
